# Generated by Django 3.2.8 on 2022-11-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('time_start', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('time_finish', models.DateTimeField(blank=True, help_text='Date updated')),
                ('winner_name', models.CharField(max_length=64, verbose_name='Winner name')),
                ('num_turns', models.IntegerField(verbose_name='Total turns')),
                ('current_turn', models.CharField(max_length=64, verbose_name='Current turn')),
                ('if_winner', models.BooleanField(default=False, help_text='Have a winner')),
                ('last_shot', models.CharField(max_length=64, verbose_name='Last shot')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=64, verbose_name='Team name')),
                ('ship_type', models.CharField(max_length=64, verbose_name='Team name')),
                ('max_health', models.IntegerField(verbose_name='Total health')),
                ('health', models.IntegerField(verbose_name='Current health')),
                ('is_alive', models.BooleanField(default=False, help_text='Is alive')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Username', max_length=64, unique=True, verbose_name='Username')),
                ('team', models.CharField(blank=True, max_length=64, null=True, verbose_name='Team name')),
                ('total_games', models.IntegerField(blank=True, null=True, verbose_name='Total games')),
                ('total_wins', models.IntegerField(blank=True, null=True, verbose_name='Total wins')),
                ('game_id', models.ForeignKey(help_text='Game', on_delete=django.db.models.deletion.CASCADE, to='projects.game')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField(blank=True, null=True, verbose_name='X coordinate')),
                ('y_coordinate', models.IntegerField(blank=True, null=True, verbose_name='Y coordinate')),
                ('team', models.CharField(max_length=20, verbose_name='Cell state')),
                ('cell_state', models.CharField(max_length=64, verbose_name='Cell state')),
                ('game_id', models.ForeignKey(help_text='Game', on_delete=django.db.models.deletion.CASCADE, to='projects.game')),
                ('ship_id', models.ForeignKey(help_text='Ship', on_delete=django.db.models.deletion.CASCADE, to='projects.ship')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=64, verbose_name='Team name')),
                ('game_id', models.ForeignKey(help_text='Game', on_delete=django.db.models.deletion.CASCADE, to='projects.game')),
            ],
        ),
    ]
