# Generated by Django 3.2.8 on 2022-11-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.ForeignKey(blank=True, help_text='Game', on_delete=django.db.models.deletion.CASCADE, to='projects.game'),
        ),
    ]
