# Generated by Django 3.2.8 on 2022-11-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_player_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.ForeignKey(blank=True, help_text='Game', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.game'),
        ),
    ]
