# Generated by Django 3.2.8 on 2022-11-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20221130_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Current turn'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_shot',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Last shot'),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_turns',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total turns'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Winner name'),
        ),
    ]
