# Generated by Django 3.2.8 on 2022-11-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_game_time_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='team',
        ),
        migrations.AddField(
            model_name='ship',
            name='board',
            field=models.ForeignKey(default=None, help_text='Game', on_delete=django.db.models.deletion.CASCADE, to='projects.board'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_type',
            field=models.CharField(max_length=64, verbose_name='Ship Type'),
        ),
    ]
