# Generated by Django 3.2.8 on 2022-11-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20221130_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='board',
            field=models.ForeignKey(default=None, help_text='Game', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.board'),
        ),
    ]
