# Generated by Django 3.2.8 on 2022-11-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_ship_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='game_id',
        ),
    ]
