# Generated by Django 3.2.8 on 2022-11-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_ship_is_alive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='game_id',
        ),
        migrations.AddField(
            model_name='cell',
            name='board',
            field=models.ForeignKey(default=None, help_text='Game', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.board'),
        ),
    ]
