# Generated by Django 3.2.8 on 2022-11-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20221130_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='team',
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_state',
            field=models.IntegerField(help_text='0,1,2,3,4', verbose_name='Cell state'),
        ),
    ]
