# Generated by Django 3.2.8 on 2022-11-30 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20221130_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='ship_id',
            field=models.ForeignKey(blank=True, default=None, help_text='Ship', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ship'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='x_coordinate',
            field=models.IntegerField(null=True, verbose_name='X coordinate'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='y_coordinate',
            field=models.IntegerField(null=True, verbose_name='Y coordinate'),
        ),
    ]
