# Generated by Django 3.2.8 on 2022-11-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20221130_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='have_ship',
            field=models.BooleanField(default=False, help_text='Have ship'),
        ),
    ]
