# Generated by Django 3.2.8 on 2022-11-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_cell_hitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_id',
        ),
        migrations.AddField(
            model_name='player',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Game', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.board'),
        ),
    ]
