# Generated by Django 3.2.8 on 2022-12-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Game', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.board'),
        ),
    ]
