# Generated by Django 3.2.8 on 2022-12-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_player_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=64)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
