# Generated by Django 3.2.8 on 2022-12-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_gameerror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['id'], 'verbose_name': 'Cell', 'verbose_name_plural': 'Cells'},
        ),
    ]
